### ISSUE TITLE
K is not defined while trying to run build_model function.

### ISSUE THREAD

**Issue by pratik-dani** [llSourcell/Make_Money_with_Tensorflow_2.0#8]

**Comment by yen936** [comment]
NameError                                 Traceback (most recent call last)
<ipython-input-74-37643215ce3b> in <module>()
----> 1 multi_head = build_model()

<ipython-input-73-c8367afe8d08> in build_model()
      6     x = Bidirectional(LSTM(64, return_sequences=True))(x)
      7 
----> 8     x, slf_attn = MultiHeadAttention(n_head=3, d_model=300, d_k=64, d_v=64, dropout=0.1)(x, x, x)
      9 
     10     avg_pool = GlobalAveragePooling1D()(x)

<ipython-input-72-81900c6d3714> in __call__(self, q, k, v, mask)
     94             if mask is not None:
     95                 mask = Lambda(lambda x:K.repeat_elements(x, n_head, 0))(mask)
---> 96             head, attn = self.attention(qs, ks, vs, mask=mask)
     97 
     98             def reshape2(x):

<ipython-input-72-81900c6d3714> in __call__(self, q, k, v, mask)
     40         self.dropout = Dropout(attn_dropout)
     41     def __call__(self, q, k, v, mask):
---> 42         attn = Lambda(lambda x:K.batch_dot(x[0],x[1],axes=[2,2])/self.temper)([q, k])
     43         if mask is not None:
     44             mmask = Lambda(lambda x:(-1e+10)*(1-x))(mask)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    610                       base_layer_utils.AutoAddUpdates(self,
    611                                                       inputs)) as auto_updater:
--> 612                 outputs = self.call(inputs, *args, **kwargs)
    613                 auto_updater.set_outputs(outputs)
    614 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py in call(self, inputs, mask)
    766     if generic_utils.has_arg(self.function, 'mask'):
    767       arguments['mask'] = mask
--> 768     return self.function(inputs, **arguments)
    769 
    770   def compute_mask(self, inputs, mask=None):

<ipython-input-72-81900c6d3714> in <lambda>(x)
     40         self.dropout = Dropout(attn_dropout)
     41     def __call__(self, q, k, v, mask):
---> 42         attn = Lambda(lambda x:K.batch_dot(x[0],x[1],axes=[2,2])/self.temper)([q, k])
     43         if mask is not None:
     44             mmask = Lambda(lambda x:(-1e+10)*(1-x))(mask)

NameError: name 'K' is not defined

**Comment by yen936** [comment]
`NameError                                 Traceback (most recent call last)
<ipython-input-74-37643215ce3b> in <module>()
----> 1 multi_head = build_model()

<ipython-input-73-c8367afe8d08> in build_model()
      6     x = Bidirectional(LSTM(64, return_sequences=True))(x)
      7 
----> 8     x, slf_attn = MultiHeadAttention(n_head=3, d_model=300, d_k=64, d_v=64, dropout=0.1)(x, x, x)
      9 
     10     avg_pool = GlobalAveragePooling1D()(x)

<ipython-input-72-81900c6d3714> in __call__(self, q, k, v, mask)
     94             if mask is not None:
     95                 mask = Lambda(lambda x:K.repeat_elements(x, n_head, 0))(mask)
---> 96             head, attn = self.attention(qs, ks, vs, mask=mask)
     97 
     98             def reshape2(x):

<ipython-input-72-81900c6d3714> in __call__(self, q, k, v, mask)
     40         self.dropout = Dropout(attn_dropout)
     41     def __call__(self, q, k, v, mask):
---> 42         attn = Lambda(lambda x:K.batch_dot(x[0],x[1],axes=[2,2])/self.temper)([q, k])
     43         if mask is not None:
     44             mmask = Lambda(lambda x:(-1e+10)*(1-x))(mask)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    610                       base_layer_utils.AutoAddUpdates(self,
    611                                                       inputs)) as auto_updater:
--> 612                 outputs = self.call(inputs, *args, **kwargs)
    613                 auto_updater.set_outputs(outputs)
    614 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py in call(self, inputs, mask)
    766     if generic_utils.has_arg(self.function, 'mask'):
    767       arguments['mask'] = mask
--> 768     return self.function(inputs, **arguments)
    769 
    770   def compute_mask(self, inputs, mask=None):

<ipython-input-72-81900c6d3714> in <lambda>(x)
     40         self.dropout = Dropout(attn_dropout)
     41     def __call__(self, q, k, v, mask):
---> 42         attn = Lambda(lambda x:K.batch_dot(x[0],x[1],axes=[2,2])/self.temper)([q, k])
     43         if mask is not None:
     44             mmask = Lambda(lambda x:(-1e+10)*(1-x))(mask)

NameError: name 'K' is not defined`

**Comment by yen936** [comment]
`

    def build_model():
    inp = Input(shape = (SEQ_LEN, 1))
    
    # LSTM before attention layers
    x = Bidirectional(LSTM(128, return_sequences=True))(inp)
    x = Bidirectional(LSTM(64, return_sequences=True))(x) 
        
    x, slf_attn = MultiHeadAttention(n_head=3, d_model=300, d_k=64, d_v=64, dropout=0.1)(x, x, x)
        
    avg_pool = GlobalAveragePooling1D()(x)
    max_pool = GlobalMaxPooling1D()(x)
    conc = concatenate([avg_pool, max_pool])
    conc = Dense(64, activation="relu")(conc)
    x = Dense(1, activation="sigmoid")(conc)      

    model = Model(inputs = inp, outputs = x)
    model.compile(
        loss = "mean_squared_error", 
        #optimizer = Adam(lr = config["lr"], decay = config["lr_d"]), 
        optimizer = "adam")
    
    # Save entire model to a HDF5 file
    #model.save('my_model.h5')
    
    return model
    multi_head = build_model()
`

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-74-37643215ce3b> in <module>()
----> 1 multi_head = build_model()

<ipython-input-73-c8367afe8d08> in build_model()
      6     x = Bidirectional(LSTM(64, return_sequences=True))(x)
      7 
----> 8     x, slf_attn = MultiHeadAttention(n_head=3, d_model=300, d_k=64, d_v=64, dropout=0.1)(x, x, x)
      9 
     10     avg_pool = GlobalAveragePooling1D()(x)

<ipython-input-72-81900c6d3714> in __call__(self, q, k, v, mask)
     94             if mask is not None:
     95                 mask = Lambda(lambda x:K.repeat_elements(x, n_head, 0))(mask)
---> 96             head, attn = self.attention(qs, ks, vs, mask=mask)
     97 
     98             def reshape2(x):

<ipython-input-72-81900c6d3714> in __call__(self, q, k, v, mask)
     40         self.dropout = Dropout(attn_dropout)
     41     def __call__(self, q, k, v, mask):
---> 42         attn = Lambda(lambda x:K.batch_dot(x[0],x[1],axes=[2,2])/self.temper)([q, k])
     43         if mask is not None:
     44             mmask = Lambda(lambda x:(-1e+10)*(1-x))(mask)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    610                       base_layer_utils.AutoAddUpdates(self,
    611                                                       inputs)) as auto_updater:
--> 612                 outputs = self.call(inputs, *args, **kwargs)
    613                 auto_updater.set_outputs(outputs)
    614 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py in call(self, inputs, mask)
    766     if generic_utils.has_arg(self.function, 'mask'):
    767       arguments['mask'] = mask
--> 768     return self.function(inputs, **arguments)
    769 
    770   def compute_mask(self, inputs, mask=None):

<ipython-input-72-81900c6d3714> in <lambda>(x)
     40         self.dropout = Dropout(attn_dropout)
     41     def __call__(self, q, k, v, mask):
---> 42         attn = Lambda(lambda x:K.batch_dot(x[0],x[1],axes=[2,2])/self.temper)([q, k])
     43         if mask is not None:
     44             mmask = Lambda(lambda x:(-1e+10)*(1-x))(mask)

NameError: name 'K' is not defined

**Comment by mwpwalshe** [comment]
Fix by adding to top
from keras import backend as K
